# Generated by Django 4.2.7 on 2023-12-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_textmessage_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='opted_in',
            field=models.BooleanField(default=False),
        ),
    ]
