# Generated by Django 4.2.7 on 2023-12-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_phonenumber_opted_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='sub_group',
            field=models.BooleanField(default=False),
        ),
    ]
