# Generated by Django 4.2.7 on 2023-12-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_phonenumber_sub_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetracker',
            name='sent_info_message_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagetracker',
            name='sent_info_message_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagetracker',
            name='sent_info_message_5',
            field=models.BooleanField(default=False),
        ),
    ]
