# Generated by Django 4.2.7 on 2023-12-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_messagetracker_sent_info_message_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetracker',
            name='sent_final_pilot_message',
            field=models.BooleanField(default=False),
        ),
    ]
