# Generated by Django 4.2.7 on 2023-12-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_messagetracker_sent_final_pilot_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetracker',
            name='sent_final_pilot_message',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='final_pilot_message_sent',
            field=models.BooleanField(default=False),
        ),
    ]
