# Generated by Django 4.2.7 on 2023-12-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_messagetracker_sent_final_pilot_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='post_survey',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='pre_survey',
            field=models.URLField(blank=True, null=True),
        ),
    ]
